# Generated by Django 5.1.4 on 2025-01-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('house_no', models.CharField(max_length=50)),
                ('floor_no', models.CharField(blank=True, max_length=50, null=True)),
                ('block_sector', models.CharField(blank=True, max_length=100, null=True)),
                ('flat_no', models.CharField(blank=True, max_length=50, null=True)),
                ('road_street', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('delivery_notes', models.TextField(blank=True, null=True)),
                ('label', models.CharField(choices=[('Home', 'Home'), ('Work', 'Work'), ('Partner', 'Partner'), ('Other', 'Other')], max_length=50)),
            ],
        ),
    ]
