# Generated by Django 5.1.4 on 2025-01-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('license_number', models.CharField(max_length=20, unique=True)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('vehicle_class', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nid_number', models.CharField(max_length=20, unique=True)),
                ('dob', models.DateField()),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('passport_number', models.CharField(max_length=20, unique=True)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('nationality', models.CharField(max_length=100)),
            ],
        ),
    ]
